### ISSUE TITLE
Submitting only one parameter, there is no output at all

### ISSUE THREAD

**Issue by voxik** [xsuchy/create-fake-rpm#2]
~~~
$ create-fake-rpm jre=1.8.0 

$ ll
total 0
~~~

This is confusing. It took me a while to realize there should also be the package name specified. I had to comment out the [`2>/dev/null`](https://github.com/xsuchy/create-fake-rpm/blob/d4f77adae90061fc5ab1e711e36dcc7395b02262/create-fake-rpm#L53) to unveil my mistake:

~~~
$ ./create-fake-rpm jre=1.8.0 
error: Macro %fake_provides has empty body
~~~

I think this would deserve improvement :innocent:

**Comment by xsuchy** [comment]
Thank you for the report.
